# Generated by Django 6.0 on 2025-12-15 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0007_function_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(blank=True, max_length=10, null=True, verbose_name='Matrícula')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='Admissão')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('phrase', models.CharField(blank=True, max_length=250, null=True, verbose_name='Frase de Perfil')),
                ('public', models.BooleanField(default=True, verbose_name='Perfil Público')),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Function', to='skills.function', verbose_name='Cargo Efetivo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Alteração')),
                ('certification_type', models.CharField(choices=[('technical', 'Curso Técnico'), ('graduation', 'Graduação'), ('postgraduation', 'Pós-graduação'), ('mba', 'MBA'), ('master', 'Mestrado'), ('doctorate', 'Doutorado'), ('postdoctorate', 'Pós-doutorado'), ('course', 'Curso'), ('training', 'Treinamento'), ('workshop-Oficina', 'Workshop/Oficina')], default='course', max_length=20, verbose_name='Tipo de Certificação')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Certificação')),
                ('institution', models.CharField(max_length=200, verbose_name='Instituição')),
                ('workload', models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga Horária')),
                ('issue_date', models.DateField(verbose_name='Data de Emissão')),
                ('file', models.FileField(blank=True, null=True, upload_to='certifications/%Y/%m/', verbose_name='Arquivo (PDF)')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Certificado')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='profiles.profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ('-issue_date',),
            },
        ),
        migrations.CreateModel(
            name='ProfileSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Alteração')),
                ('level', models.IntegerField(choices=[(0, 'Robótico'), (1, 'Básico'), (2, 'Intermediário'), (3, 'Avançado'), (4, 'Especialista')], default=0, verbose_name='Nível')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.profile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='skills.skill', verbose_name='Habilidade')),
            ],
            options={
                'verbose_name': 'Habilidade do Perfil',
                'verbose_name_plural': 'Habilidades por Perfil',
                'ordering': ('-level', 'skill'),
                'unique_together': {('profile', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='ProfileSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Alteração')),
                ('level', models.IntegerField(choices=[(0, 'Robótico'), (1, 'Básico'), (2, 'Intermediário'), (3, 'Avançado'), (4, 'Especialista')], default=0, verbose_name='Nível')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='profiles.profile', verbose_name='Perfil')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='skills.system', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Sistema do Perfil',
                'verbose_name_plural': 'Sistemas por Perfil',
                'ordering': ('-level', 'system'),
                'unique_together': {('profile', 'system')},
            },
        ),
    ]
