# Generated by Django 6.0 on 2025-12-10 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(blank=True, max_length=150, verbose_name='Setor Atual')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Alteração')),
                ('certification_type', models.CharField(choices=[('technical', 'Curso Técnico'), ('graduation', 'Graduação'), ('postgraduation', 'Pós-graduação'), ('mba', 'MBA'), ('master', 'Mestrado'), ('doctorate', 'Doutorado'), ('postdoctorate', 'Pós-doutorado'), ('course', 'Curso'), ('training', 'Treinamento'), ('workshop-Oficina', 'Workshop/Oficina')], default='course', max_length=20, verbose_name='Tipo de Certificação')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Certificação')),
                ('institution', models.CharField(max_length=200, verbose_name='Instituição')),
                ('workload', models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga Horária (horas)')),
                ('issue_date', models.DateField(verbose_name='Data de Emissão')),
                ('file', models.FileField(blank=True, null=True, upload_to='certifications/%Y/%m/', verbose_name='Arquivo (PDF)')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Certificado')),
                ('skills', models.ManyToManyField(blank=True, related_name='profile_certifications', to='skills.skill')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='profiles.profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ('-issue_date',),
            },
        ),
        migrations.CreateModel(
            name='ProfileSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('basic', 'Básico'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado'), ('expert', 'Especialista')], max_length=20)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.profile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='skills.skill')),
            ],
            options={
                'unique_together': {('profile', 'skill')},
            },
        ),
    ]
