# Generated by Django 6.0 on 2025-12-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profileskill_options_profileskill_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sector',
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=150, verbose_name='Cargo'),
        ),
    ]
