# Generated by Django 6.0 on 2025-12-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_sector_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration',
            field=models.CharField(blank=True, max_length=10, verbose_name='Matrícula'),
        ),
    ]
