# Generated by Django 6.0 on 2025-12-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='skills',
        ),
    ]
