# Generated by Django 6.0 on 2025-12-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_certification_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Admissão'),
        ),
    ]
