# Generated by Django 6.0 on 2025-12-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registration',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Matrícula'),
        ),
    ]
