# Generated by Django 6.0 on 2025-12-11 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_registration'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='workload',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga Horária'),
        ),
        migrations.CreateModel(
            name='ProfileSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(blank=True, max_length=50, verbose_name='Nível de Acesso')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='profiles.profile', verbose_name='Perfil')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='skills.system', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Sistema do Perfil',
                'verbose_name_plural': 'Sistemas por Perfil',
                'ordering': ('profile', 'system'),
                'unique_together': {('profile', 'system')},
            },
        ),
    ]
