# Generated by Django 6.0 on 2025-12-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_profile_registration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileskill',
            options={'ordering': ('profile', 'skill')},
        ),
        migrations.RemoveField(
            model_name='profileskill',
            name='order',
        ),
        migrations.RemoveField(
            model_name='profileskill',
            name='years_experience',
        ),
        migrations.AddField(
            model_name='profileskill',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
    ]
