# Generated by Django 6.0 on 2025-12-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_alter_profileskill_options_remove_profileskill_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileskill',
            options={'ordering': ('profile', 'skill', 'level')},
        ),
        migrations.AlterModelOptions(
            name='profilesystem',
            options={'ordering': ('profile', 'system', 'level'), 'verbose_name': 'Sistema do Perfil', 'verbose_name_plural': 'Sistemas por Perfil'},
        ),
    ]
