# Generated by Django 6.0 on 2025-12-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_alter_profileskill_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileskill',
            options={'ordering': ('level', 'skill')},
        ),
        migrations.AlterModelOptions(
            name='profilesystem',
            options={'ordering': ('level', 'system'), 'verbose_name': 'Sistema do Perfil', 'verbose_name_plural': 'Sistemas por Perfil'},
        ),
    ]
