# Generated by Django 6.0 on 2025-12-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_profileskill_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileskill',
            options={'ordering': ('-level', 'skill'), 'verbose_name': 'Habilidade do Perfil', 'verbose_name_plural': 'Habilidades por Perfil'},
        ),
        migrations.AlterModelOptions(
            name='profilesystem',
            options={'ordering': ('-level', 'system'), 'verbose_name': 'Sistema do Perfil', 'verbose_name_plural': 'Sistemas por Perfil'},
        ),
    ]
