# Generated by Django 6.0 on 2025-12-13 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_alter_profileskill_options_and_more'),
        ('skills', '0004_remove_system_owner_sector_function_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Function', to='skills.function', verbose_name='Cargo Efetivo'),
        ),
        migrations.AlterField(
            model_name='profileskill',
            name='level',
            field=models.IntegerField(choices=[(0, 'Robótico'), (1, 'Básico'), (2, 'Intermediário'), (3, 'Avançado'), (4, 'Especialista')], default=1, verbose_name='Nível'),
        ),
        migrations.AlterField(
            model_name='profilesystem',
            name='level',
            field=models.IntegerField(choices=[(0, 'Robótico'), (1, 'Básico'), (2, 'Intermediário'), (3, 'Avançado'), (4, 'Especialista')], default=1, verbose_name='Nível'),
        ),
    ]
