# Generated by Django 6.0 on 2025-12-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_profile_phrase_alter_profileskill_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phrase',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Frase de Perfil'),
        ),
    ]
