# Generated by Django 6.0 on 2025-12-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_remove_talent_categories_delete_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talentskill',
            options={'verbose_name': 'Habilidade do Servidor', 'verbose_name_plural': 'Habilidades do Servidor'},
        ),
        migrations.RemoveField(
            model_name='certification',
            name='talent',
        ),
        migrations.AddField(
            model_name='certification',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='certifications', to='curriculum.skill'),
        ),
        migrations.AddField(
            model_name='talent',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='talents', to='curriculum.certification'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='talents', through='curriculum.TalentSkill', to='curriculum.skill'),
        ),
    ]
